#!/usr/bin/env node

// generate-models.ts — 纯本地聚合,零联网。
//
// 公司内部项目:模型订阅源是仓库内已提交的 src/providers/*.models.ts
// (本地静态数据)。本脚本只做聚合——扫描这些文件,生成 src/models.generated.ts
// (import 全部 provider 常量 + 聚合成 MODELS 对象)。
//
// 不联网、不删除 provider 文件。这样 build 永远稳定,与网络无关。
//
// 历史问题:旧版本联网拉 models.dev/OpenRouter/Vercel AI Gateway/NVIDIA,
// 先 rmSync 删光 *.models.ts 再按拉取结果重写。任一 API 失败(如 Vercel
// 不可达)→ 对应 provider 文件不生成 → import 失败 TS2307 → MODELS 类型
// 推断崩坏 → all.ts:44 TS2536,让 package-all/publish 整个崩掉。

import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");

/** provider id → 常量名,与旧版完全一致(连续非字母数字 → 单个 _)。 */
function catalogConstName(providerId: string): string {
	return `${providerId.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_MODELS`;
}

function generateModels(): void {
	const providersDir = join(packageRoot, "src", "providers");
	const generatedHeader = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

`;

	// 扫描本地已提交的 provider 订阅源,按 provider id 排序保证确定性输出。
	const providerIds = readdirSync(providersDir)
		.filter((entry) => entry.endsWith(".models.ts"))
		.map((entry) => entry.slice(0, -".models.ts".length))
		.sort();

	if (providerIds.length === 0) {
		throw new Error(
			`No provider catalogs found under ${providersDir}. ` +
				"src/providers/*.models.ts are the local subscription source — they must be committed.",
		);
	}

	// 聚合文件:import 每个 provider 的常量,再聚合成 MODELS。
	let output = generatedHeader;
	for (const providerId of providerIds) {
		const constName = catalogConstName(providerId);
		output += `import { ${constName} } from "./providers/${providerId}.models.ts";\n`;
	}
	output += `\nexport const MODELS = {\n`;
	for (const providerId of providerIds) {
		output += `\t${JSON.stringify(providerId)}: ${catalogConstName(providerId)},\n`;
	}
	output += `} as const;\n`;

	const outPath = join(packageRoot, "src", "models.generated.ts");
	writeFileSync(outPath, output);
	console.log(`Generated ${outPath} (${providerIds.length} providers)`);

	console.log("\nModel catalog (local subscription source):");
	for (const providerId of providerIds) {
		console.log(`  ${providerId}`);
	}
}

generateModels();
